language: python

python:
    - "3.6"

before_install:
    - pip install pytest pytest-cov
    - pip install codecov

script:
    - pytest --cov-report=xml --cov=Git-fighters tests/

after_success:
    - codecov
