language: python

python:
    - "3.6"

before_install:
    - pip install pytest pytest-cov
    - pip install codecov

script:
    - pytest --cov-report=xml --cov=./

env:
    - CODECOV_TOKEN="7e8bbc89-aba6-4a10-8b4f-39e6d15da7a3"

after_success:
    - codecov

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDQxZmY4YWIzLWYxZjYtNDJiNi1hY2NjLWIzNjdkMmIxNzA2MQACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgHihpDvoiFOalAsmVl12eL9v5CPb3WDAFOagZnnqwQ1A"